[package]
name = "tracked-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.11"

[dev-dependencies]
log = "0.4.17"
simple_logger = "2.3.0"
